name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '15 0 * * 6'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:  
  build-docker-images:    
    name: Build Docker Images
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU        
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx        
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Package Registry        
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ REGISTRY }} -u ${{ github.actor }} --password-stdin
    - name: Build & Push Docker image
      run: docker buildx build -t ghcr.io/${{ github.repository_owner }}/${{ IMAGE_NAME }}:latest -f Dockerfile --push --platform=linux/arm64,linux/amd64 .
